import argparse
import json
import os
from modules.paths_internal import normalized_filepath, models_path, script_path, data_path, extensions_dir, extensions_builtin_dir, sd_default_config, sd_model_file  # noqa: F401

parser = argparse.ArgumentParser()

parser.add_argument("-f", action='store_true', help=argparse.SUPPRESS)  # root権限での実行を許可（webuiの外部で実装）
parser.add_argument("--update-all-extensions", action='store_true', help="launch.py 引数: プログラム起動時にすべての拡張機能の更新をダウンロードする")
parser.add_argument("--skip-python-version-check", action='store_true', help="launch.py 引数: python version をチェックしない")
parser.add_argument("--skip-torch-cuda-test", action='store_true', help="launch.py 引数: CUDA が正常に動作するかチェックしない")
parser.add_argument("--reinstall-xformers", action='store_true', help="launch.py 引数: 既にインストールされているバージョンに関わらず、適切なバージョンの xformers をインストールする")
parser.add_argument("--reinstall-torch", action='store_true', help="launch.py 引数: 既にインストールされているバージョンに関わらず、適切なバージョンの torch をインストールする")
parser.add_argument("--update-check", action='store_true', help="launch.py 引数: 起動時に更新を確認する")
parser.add_argument("--test-server", action='store_true', help="launch.py 引数: テスト用にサーバーを構成する")
parser.add_argument("--log-startup", action='store_true', help="launch.py 引数: 起動時に何が起こっているかの詳細なログを表示する")
parser.add_argument("--skip-prepare-environment", action='store_true', help="launch.py 引数: すべての環境準備をスキップする")
parser.add_argument("--skip-install", action='store_true', help="launch.py 引数: パッケージのインストールをスキップする")
parser.add_argument("--dump-sysinfo", action='store_true', help="launch.py 引数: 拡張機能とオプションの情報なしで制限されたシステム情報ファイルをディスクにダンプして終了する")
parser.add_argument("--loglevel", type=str, help="ログレベル; 以下のいずれか: CRITICAL、ERROR、WARNING、INFO、DEBUG", default=None)
parser.add_argument("--do-not-download-clip", action='store_true', help="チェックポイントに含まれていなくても、CLIPモデルをダウンロードしないでください")
parser.add_argument("--data-dir", type=normalized_filepath, default=os.path.dirname(os.path.dirname(os.path.realpath(__file__))), help="すべてのユーザーデータが保存される基本パス")
parser.add_argument("--models-dir", type=normalized_filepath, default=None, help="モデルが保存されている基本パス; --data-dirを上書きします")
parser.add_argument("--config", type=normalized_filepath, default=sd_default_config, help="モデルを構築する設定へのパス",)
parser.add_argument("--ckpt", type=normalized_filepath, default=sd_model_file, help="Stable Diffusionモデルのチェックポイントへのパス; 指定された場合、このチェックポイントはチェックポイントのリストに追加され、読み込まれます",)
parser.add_argument("--ckpt-dir", type=normalized_filepath, default=None, help="Stable Diffusionのチェックポイントがあるディレクトリへのパス")
parser.add_argument("--vae-dir", type=normalized_filepath, default=None, help="VAEファイルがあるディレクトリへのパス")
parser.add_argument("--gfpgan-dir", type=normalized_filepath, help="GFPGANのディレクトリ", default=('./src/gfpgan' if os.path.exists('./src/gfpgan') else './GFPGAN'))
parser.add_argument("--gfpgan-model", type=normalized_filepath, help="GFPGANモデルのファイル名", default=None)
parser.add_argument("--no-half", action='store_true', help="モデルを16-bit floatに切り替えない")
parser.add_argument("--no-half-vae", action='store_true', help="VAEモデルを16-bit floatに切り替えない")
parser.add_argument("--no-progressbar-hiding", action='store_true', help="GradioのUIでプログレスバーを隠さないでください（ブラウザでハードウェアアクセラレーションを使用している場合、MLの動作が遅くなるため隠しています）")
parser.add_argument("--max-batch-count", type=int, default=16, help="何もしない")
parser.add_argument("--embeddings-dir", type=normalized_filepath, default=os.path.join(data_path, 'embeddings'), help="テキスト反転用の埋め込みディレクトリ（デフォルト：embeddings）")
parser.add_argument("--textual-inversion-templates-dir", type=normalized_filepath, default=os.path.join(script_path, 'textual_inversion_templates'), help="テキスト反転テンプレートが保存されているディレクトリ")
parser.add_argument("--hypernetwork-dir", type=normalized_filepath, default=os.path.join(models_path, 'hypernetworks'), help="hypernetworkディレクトリ")
parser.add_argument("--localizations-dir", type=normalized_filepath, default=os.path.join(script_path, 'localizations'), help="localizationsディレクトリ")
parser.add_argument("--allow-code", action='store_true', help="webuiからのカスタムスクリプト実行を許可する")
parser.add_argument("--medvram", action='store_true', help="VRAM使用量を減らすため、速度を少し犠牲にしてStable Diffusionモデルを最適化する")
parser.add_argument("--medvram-sdxl", action='store_true', help="SDXLモデルにのみ--medvramの最適化を適用する")
parser.add_argument("--lowvram", action='store_true', help="VRAM使用量を大幅に減らすため、速度を大きく犠牲にしてStable Diffusionモデルを最適化する")
parser.add_argument("--lowram", action='store_true', help="Stable Diffusionのチェックポイントの重みをRAMではなくVRAMに読み込む")
parser.add_argument("--always-batch-cond-uncond", action='store_true', help="何もしない（互換性のために残されています）")
parser.add_argument("--unload-gfpgan", action='store_true', help="何もしない（互換性のために残されています）")
parser.add_argument("--precision", type=str, help="計算精度", choices=["full", "half", "autocast"], default="autocast")
parser.add_argument("--upcast-sampling", action='store_true', help="サンプリング時にアップキャストする。--no-half指定時は効果がない。通常はメモリ使用量を抑えつつ、--no-halfと同程度の結果をより高い性能で得られる")
parser.add_argument("--share", action='store_true', help="Gradioでshare=Trueを使用し、Gradioのサイト経由でUIにアクセスできるようにする")
parser.add_argument("--ngrok", type=str, help="Gradioの--shareの代わりに使用するngrokの認証トークン", default=None)
parser.add_argument("--ngrok-region", type=str, help="何もしない（互換性のために残されています）", default="")
parser.add_argument("--ngrok-options", type=json.loads, help='ngrokに渡すオプション（JSON形式）。例: \'{"authtoken_from_env":true, "basic_auth":"user:password", "oauth_provider":"google", "oauth_allow_emails":"user@asdf.com"}\'', default=dict())
parser.add_argument("--enable-insecure-extension-access", action='store_true', help="他の設定に関係なく拡張機能タブを有効にする")
parser.add_argument("--codeformer-models-path", type=normalized_filepath, help="CodeFormerモデルファイルがあるディレクトリへのパス", default=os.path.join(models_path, 'Codeformer'))
parser.add_argument("--gfpgan-models-path", type=normalized_filepath, help="GFPGANモデルファイルがあるディレクトリへのパス", default=os.path.join(models_path, 'GFPGAN'))
parser.add_argument("--esrgan-models-path", type=normalized_filepath, help="ESRGANモデルファイルがあるディレクトリへのパス", default=os.path.join(models_path, 'ESRGAN'))
parser.add_argument("--bsrgan-models-path", type=normalized_filepath, help="BSRGANモデルファイルがあるディレクトリへのパス", default=os.path.join(models_path, 'BSRGAN'))
parser.add_argument("--realesrgan-models-path", type=normalized_filepath, help="RealESRGANモデルファイルがあるディレクトリへのパス", default=os.path.join(models_path, 'RealESRGAN'))
parser.add_argument("--dat-models-path", type=normalized_filepath, help="DATモデルファイルがあるディレクトリへのパス", default=os.path.join(models_path, 'DAT'))
parser.add_argument("--clip-models-path", type=normalized_filepath, help="CLIPモデルファイルがあるディレクトリへのパス", default=None)
parser.add_argument("--xformers", action='store_true', help="クロスアテンション層でxformersを有効にする")
parser.add_argument("--force-enable-xformers", action='store_true', help="検査コードで実行可能と判定されなくても、クロスアテンション層でxformersを強制的に有効にする。動作しない場合はバグ報告を行わないこと")
parser.add_argument("--xformers-flash-attention", action='store_true', help="再現性を高めるため、Flash Attentionを使用するxformersを有効にする（SD2.xまたはその派生モデルのみ対応）")
parser.add_argument("--deepdanbooru", action='store_true', help="何もしない（互換性のために残されています）")
parser.add_argument("--opt-split-attention", action='store_true', help="最適化方式を自動選択する際に、Doggettxのクロスアテンション層最適化を優先する")
parser.add_argument("--opt-sub-quad-attention", action='store_true', help="最適化方式を自動選択する際に、メモリ効率の高い二次未満のクロスアテンション層最適化を優先する")
parser.add_argument("--sub-quad-q-chunk-size", type=int, help="二次未満のクロスアテンション層最適化で使用するクエリのチャンクサイズ", default=1024)
parser.add_argument("--sub-quad-kv-chunk-size", type=int, help="二次未満のクロスアテンション層最適化で使用するKVのチャンクサイズ", default=None)
parser.add_argument("--sub-quad-chunk-threshold", type=int, help="二次未満のクロスアテンション層最適化でチャンク分割を使用するVRAM使用率のしきい値（パーセント）", default=None)
parser.add_argument("--opt-split-attention-invokeai", action='store_true', help="最適化方式を自動選択する際に、InvokeAIのクロスアテンション層最適化を優先する")
parser.add_argument("--opt-split-attention-v1", action='store_true', help="最適化方式を自動選択する際に、旧バージョンの分割アテンション最適化を優先する")
parser.add_argument("--opt-sdp-attention", action='store_true', help="最適化方式を自動選択する際に、scaled dot productによるクロスアテンション層最適化を優先する。PyTorch 2.*が必要")
parser.add_argument("--opt-sdp-no-mem-attention", action='store_true', help="最適化方式を自動選択する際に、メモリ効率化を行わないscaled dot productによるクロスアテンション層最適化を優先する。画像生成が決定論的になる。PyTorch 2.*が必要")
parser.add_argument("--disable-opt-split-attention", action='store_true', help="最適化方式を自動選択する際に、クロスアテンション層の最適化を使用しないことを優先する")
parser.add_argument("--disable-nan-check", action='store_true', help="生成画像や潜在空間にNaNが含まれているかチェックしない。チェックポイントなしでCIを実行する場合に便利")
parser.add_argument("--use-cpu", nargs='+', help="指定したモジュールでCPUをtorchのデバイスとして使用する", default=[], type=str.lower)
parser.add_argument("--use-ipex", action="store_true", help="Intel XPUをtorchのデバイスとして使用する")
parser.add_argument("--disable-model-loading-ram-optimization", action='store_true', help="モデル読み込み時のRAM使用量を減らす最適化を無効にする")
parser.add_argument("--listen", action='store_true', help="サーバー名に0.0.0.0を指定してGradioを起動し、ネットワークからのリクエストに応答できるようにする")
parser.add_argument("--port", type=int, help="Gradioを指定したサーバーポートで起動する。1024未満のポートにはroot/管理者権限が必要。利用可能な場合のデフォルトは7860", default=None)
parser.add_argument("--show-negative-prompt", action='store_true', help="何もしない（互換性のために残されています）", default=False)
parser.add_argument("--ui-config-file", type=str, help="UI設定に使用するファイル名", default=os.path.join(data_path, 'ui-config.json'))
parser.add_argument("--hide-ui-dir-config", action='store_true', help="webuiでディレクトリ設定を非表示にする", default=False)
parser.add_argument("--freeze-settings", action='store_true', help="すべての設定を全体的に編集不可にする", default=False)
parser.add_argument("--freeze-settings-in-sections", type=str, help='設定ページの特定セクションの設定を編集不可にする。「saving-images,upscaling」のようにカンマ区切りで指定する。設定名の一覧はmodules/shared_options.pyにある', default=None)
parser.add_argument("--freeze-specific-settings", type=str, help='個別の設定を編集不可にする。「samples_save,samples_format」のようにカンマ区切りで指定する。設定名の一覧はconfig.jsonにある', default=None)
parser.add_argument("--ui-settings-file", type=str, help="UI設定に使用するファイル名", default=os.path.join(data_path, 'config.json'))
parser.add_argument("--gradio-debug",  action='store_true', help="--debugオプションを付けてGradioを起動する")
parser.add_argument("--gradio-auth", type=str, help='Gradioの認証を「username:password」の形式で設定する。複数指定する場合は「u1:p1,u2:p2,u3:p3」のようにカンマで区切る', default=None)
parser.add_argument("--gradio-auth-path", type=normalized_filepath, help='Gradioの認証ファイルのパス。例: "/path/to/auth/file"。形式は--gradio-authと同じ', default=None)
parser.add_argument("--gradio-img2img-tool", type=str, help='何もしない（互換性のために残されています）')
parser.add_argument("--gradio-inpaint-tool", type=str, help="何もしない（互換性のために残されています）")
parser.add_argument("--gradio-allowed-path", action='append', help="Gradioのallowed_pathsにパスを追加し、そのパスからファイルを提供できるようにする", default=[data_path])
parser.add_argument("--opt-channelslast", action='store_true', help="Stable Diffusionのメモリ形式をchannels lastに変更する")
parser.add_argument("--styles-file", type=str, action='append', help="スタイルファイルのパスまたはワイルドカード。複数指定可能", default=[])
parser.add_argument("--autolaunch", action='store_true', help="起動時にシステムの既定ブラウザーでwebuiのURLを開く", default=False)
parser.add_argument("--theme", type=str, help="ライトまたはダークのテーマでUIを起動する", default=None)
parser.add_argument("--use-textbox-seed", action='store_true', help="UIのシードにテキストボックスを使用する（上下ボタンはないが、長いシードを入力できる）", default=False)
parser.add_argument("--disable-console-progressbars", action='store_true', help="コンソールにプログレスバーを出力しない", default=False)
parser.add_argument("--enable-console-prompts", action='store_true', help="何もしない（互換性のために残されています）", default=False)  # Legacy compatibility, use as default value shared.opts.enable_console_prompts
parser.add_argument('--vae-path', type=normalized_filepath, help='VAEとして使用するチェックポイント。この引数を設定すると、VAEに関するすべての設定が無効になる', default=None)
parser.add_argument("--disable-safe-unpickle", action='store_true', help="PyTorchモデルの悪意あるコードのチェックを無効にする", default=False)
parser.add_argument("--api", action='store_true', help="api=Trueを使用してwebuiと一緒にAPIを起動する（APIのみの場合は--nowebuiを使用）")
parser.add_argument("--api-auth", type=str, help='APIの認証を「username:password」の形式で設定する。複数指定する場合は「u1:p1,u2:p2,u3:p3」のようにカンマで区切る', default=None)
parser.add_argument("--api-log", action='store_true', help="api-log=Trueを使用して、すべてのAPIリクエストのログを有効にする")
parser.add_argument("--nowebui", action='store_true', help="webuiの代わりにapi=Trueを使用してAPIを起動する")
parser.add_argument("--ui-debug-mode", action='store_true', help="モデルを読み込まず、UIをすばやく起動する")
parser.add_argument("--device-id", type=str, help="使用する既定のCUDAデバイスを選択する（事前にCUDA_VISIBLE_DEVICES=0,1などの設定が必要な場合がある）", default=None)
parser.add_argument("--administrator", action='store_true', help="管理者権限", default=False)
parser.add_argument("--cors-allow-origins", type=str, help="許可するCORSオリジンをカンマ区切りで指定する（空白なし）", default=None)
parser.add_argument("--cors-allow-origins-regex", type=str, help="許可するCORSオリジンを1つの正規表現で指定する", default=None)
parser.add_argument("--tls-keyfile", type=str, help="TLSを部分的に有効にする。完全に機能させるには--tls-certfileが必要", default=None)
parser.add_argument("--tls-certfile", type=str, help="TLSを部分的に有効にする。完全に機能させるには--tls-keyfileが必要", default=None)
parser.add_argument("--disable-tls-verify", action="store_false", help="指定すると自己署名証明書を使用できるようにする", default=None)
parser.add_argument("--server-name", type=str, help="サーバーのホスト名を設定する", default=None)
parser.add_argument("--gradio-queue", action='store_true', help="何もしない（互換性のために残されています）", default=True)
parser.add_argument("--no-gradio-queue", action='store_true', help="Gradioのキューを無効にする。WebページがWebSocketではなくHTTPリクエストを使用するようになる。以前のバージョンではデフォルトだった")
parser.add_argument("--skip-version-check", action='store_true', help="torchとxformersのバージョンチェックを行わない")
parser.add_argument("--no-hashing", action='store_true', help="読み込み性能を向上させるため、チェックポイントのSHA-256ハッシュ計算を無効にする", default=False)
parser.add_argument("--no-download-sd-model", action='store_true', help="--ckpt-dirにモデルが見つからなくてもSD1.5モデルをダウンロードしない", default=False)
parser.add_argument('--subpath', type=str, help='Gradioのサブパスを設定する。リバースプロキシと併用する')
parser.add_argument('--add-stop-route', action='store_true', help='何もしない（互換性のために残されています）')
parser.add_argument('--api-server-stop', action='store_true', help='API経由でサーバーの停止・再起動・強制終了を有効にする')
parser.add_argument('--timeout-keep-alive', type=int, default=30, help='uvicornのtimeout_keep_aliveを設定する')
parser.add_argument("--disable-all-extensions", action='store_true', help="他の設定に関係なく、すべての拡張機能の実行を禁止する", default=False)
parser.add_argument("--disable-extra-extensions", action='store_true', help="他の設定に関係なく、組み込み以外のすべての拡張機能の実行を禁止する", default=False)
parser.add_argument("--skip-load-model-at-start", action='store_true', help="webui起動時のモデル読み込みをスキップする。--nowebui指定時のみ有効")
parser.add_argument("--unix-filenames-sanitization", action='store_true', help="ファイル名に「/」以外の任意の記号を許可する。ブラウザーやファイルシステムと競合する場合がある")
parser.add_argument("--filenames-max-length", type=int, default=128, help='保存画像のファイル名の最大長。変更するとファイルシステムと競合する場合がある')
parser.add_argument("--no-prompt-history", action='store_true', help="前回生成時のプロンプトを読み込む機能を無効にする。この引数を設定すると「--data_path/params.txt」ファイルは作成されない")
